version: "3.8"
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: names_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgAdmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:9.2
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.ru
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5000:80"
    depends_on:
      - db

volumes:
  postgres_data:
    name: postgres_data